grails-app/domain/jefersson/nunez/boleteria/Boleto.groovy
package jefersson.nunez.boleteria

class Boleto {
	static searchable = true
	Double valor
	Evento evento
	Tipo tipo
	
    static constraints = {
		
    }
	
	static mapping = {
		version false
		table 'BOLETO'
		id generator:'native'
		columns{
			id column:'ID'
			valor column:'valor'
			evento column:'evento'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/Cliente.groovy
package jefersson.nunez.boleteria

class Cliente {
	static searchable = true
	Long cedula
	String nombre
	String telefono
	String correo

    static constraints = {
		
    }
	
	static mapping = {
		version false
		table 'CLIENTE'
		id generator:'native'
		columns{
			id column:'id'
			cedula column:'cedula'
			nombre column:'nombre'
			correo column:'correo'
			telefono column:'telefono'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/Evento.groovy
package jefersson.nunez.boleteria

class Evento {
	static searchable = true
	String nombre
	String direccion
	String ciudad
	Date fecha
	Long cantidadBoletos

    static constraints = {
		nombre(nullable: false, blank: false)
		direccion(nullable: false, blank: false)
		ciudad(nullable: false, blank: false)
		fecha(nullable: false, blank: false)
		cantidadBoletos(nullable: false, blank: false)
    }
	static mapping = {
		version false
		table 'EVENTO'
		id generator:'native'
		columns{
			id column:'id'
			nombre column:'nombre'
			direccion column:'direccion'
			ciudad column:'ciudad'
			fecha column:'fecha'
			cantidadBoletos column:'cantidadBoletos'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/Reserva.groovy
package jefersson.nunez.boleteria

class Reserva {
	static searchable = true
	Cliente cliente
	Boleto boleto
	Date fecha
	Long cantidadBoletos
	
    static constraints = {
    }
	
	static mapping = {
		version false
		table 'RESERVA'
		id generator:'native'
		columns{
			id column:'id'
			cliente column:'cliente'
			boleto column:'boleto'
			fecha column:'fecha'
			cantidadBoletos column:'cantidadBoletos'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/Role.groovy
package jefersson.nunez.boleteria

/**
 * The Role entity.
 *
 * @author  Jefersson Nava
 * @version 1.0.0
 * @since
 *
 */
class Role {
	static searchable = true
    String name

    static hasMany = [ users: User, permissions: String ]
    static belongsTo = User

    static constraints = {
        name(nullable: false, blank: false, unique: true)
    }
	
	static mapping = {
		version false
		table 'ROLE'
		id generator:'native'
		columns{
			id column:'ID'
			name column:'nombre'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/Tipo.groovy
package jefersson.nunez.boleteria

class Tipo {
	static searchable = true
	String nombre

    static constraints = {
    }
	static mapping = {
		version false
		table 'TIPO'
		id generator:'native'
		columns{
			id column:'ID'
			nombre column:'valor'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/User.groovy
package jefersson.nunez.boleteria

/**
 * The User entity.
 *
 * @author  Jefersson Nava
 * @version 1.0.0
 * @since
 *
 */
class User {
	static searchable = true
	
    String username
    String passwordHash
	
	String nombre
	String apellido
    String telefono
	String fechaRegistro
	String habilitado = "S"
	
    static hasMany = [ roles: Role ]

    static constraints = {
        username(nullable: false, blank: false, unique: true)
		passwordHash nullable:false, blank:false
		nombre nullable: false, blank: false, size:1..100
		apellido nullable: true, blank: true, size:0..100
		habilitado nullable:false, blank:false, size:0..1, inList:["S","N"]
		fechaRegistro nullable:true, blank:true, size:0..1024
		telefono nullable:true, blank:true, size:1..20
    }
	
	static mapping = {
		version false
		table 'USUARIO'
		id generator:'native'
		columns{
			id column:'ID'
			username column:'usuario'
			passwordHash column:'clave'
			nombre column:'nombre'
			apellido column:'apellido'
			telefono column:'telefono'
			fechaRegistro column:'fechaRegistro'
			habilitado column:'habilitado'
		}
	}
}

grails-app/controllers/jefersson/nunez/boleteria/AuthController.groovy
package jefersson.nunez.boleteria

import org.apache.shiro.SecurityUtils
import org.apache.shiro.authc.AuthenticationException
import org.apache.shiro.authc.UsernamePasswordToken
import org.apache.shiro.web.util.SavedRequest
import org.apache.shiro.web.util.WebUtils

class AuthController {
    def shiroSecurityManager

    def index = { redirect(action: "login", params: params) }

    def login = {
        return [ username: params.username, rememberMe: (params.rememberMe != null), targetUri: params.targetUri ]
    }

    def signIn = {
        def authToken = new UsernamePasswordToken(params.username, params.password as String)

        // Support for "remember me"
        if (params.rememberMe) {
            authToken.rememberMe = true
        }
        
        // If a controller redirected to this page, redirect back
        // to it. Otherwise redirect to the root URI.
        def targetUri = params.targetUri ?: "/"
        
        // Handle requests saved by Shiro filters.
        SavedRequest savedRequest = WebUtils.getSavedRequest(request)
        if (savedRequest) {
            targetUri = savedRequest.requestURI - request.contextPath
            if (savedRequest.queryString) targetUri = targetUri + '?' + savedRequest.queryString
        }
        
        try{
            // Perform the actual login. An AuthenticationException
            // will be thrown if the username is unrecognised or the
            // password is incorrect.
            SecurityUtils.subject.login(authToken)

            log.info "Redirecting to '${targetUri}'."
            redirect(uri: targetUri)
        }
        catch (AuthenticationException ex){
            // Authentication failed, so display the appropriate message
            // on the login page.
            log.info "Authentication failure for user '${params.username}'."
            flash.message = message(code: "login.failed")

            // Keep the username and "remember me" setting so that the
            // user doesn't have to enter them again.
            def m = [ username: params.username ]
            if (params.rememberMe) {
                m["rememberMe"] = true
            }

            // Remember the target URI too.
            if (params.targetUri) {
                m["targetUri"] = params.targetUri
            }

            // Now redirect back to the login page.
            redirect(action: "login", params: m)
        }
    }

    def signOut = {
        // Log the user out of the application.
        SecurityUtils.subject?.logout()
        webRequest.getCurrentRequest().session = null

        // For now, redirect back to the home page.
        redirect(uri: "/")
    }

    def unauthorized = {
        render "You do not have permission to access this page."
    }
}

grails-app/views/role/_form.gsp
<%@ page import="jefersson.nunez.boleteria.Role" %>




<div class="form-group ${hasErrors(bean: roleInstance, field: 'name', 'error')} required">
	<label for="name" class="col-sm-4 control-label">
		<g:message code="role.name.label" default="Nombre" />
		<span class="required-indicator">*</span>
	</label>
	<div class="col-sm-8">
		<g:textField name="name" class="input-sm col-xs-8 col-sm-8" required="" value="${roleInstance?.name}"/>
	</div>
</div>

<div class="form-group ${hasErrors(bean: roleInstance, field: 'permissions', 'error')} ">
	<label for="permissions" class="col-sm-4 control-label">
		<g:message code="role.permissions.label" default="Permisos" />
	</label>
	<div class="col-sm-8">
			<input type="hidden" id="permisos" value="${roleInstance?.permissions}">
			<g:select name="permissions" id="permissions" from="" multiple="true" data-placeholder="Ninguno" optionKey="" optionValue="" value="${roleInstance?.permissions}" 
				class="chosen-select"/>
	</div>
</div>

grails-app/views/role/_listPerfiles.gsp
	<g:if test="${flash.message}">
		<div class="alert alert-info alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
			${flash.message}
		</div>
	</g:if>
	<br>
	<g:if test="${roleInstanceList.empty}">
		<p id="noEntries"><g:message code="default.noEntries.label"/></p>
	</g:if>
	<g:else>
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th class="text-center"><g:message code="role.name.label" /></th>
					<th class="text-center"><g:message code="role.permissions.label" /></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<g:each in="${roleInstanceList}" status="i" var="roleInstance">
				<tr class="${(i % 2) == 0 ? 'even' : 'odd'} fil" data-id="${roleInstance.id }">
					
					<td class="text-center">${fieldValue(bean: roleInstance, field: "name")}</td>
					<td class="text-center">
					
						<g:each in="${roleInstance.permissions}" status="x" var="permisos">
							
							<g:each in="${permisosList}" status="ix" var="permi">
							
								<g:if test="${permi.CODIGO == permisos || permisos == '*:*'}">
									${permi.NOMBRE },
								</g:if>
								
							</g:each>
							
						</g:each>
					</td>
					<td class="text-center">
						<g:link action="show" id="${roleInstance?.id}" class="btn btn-primary pull-right">
							<i class="fa fa-search-plus" aria-hidden="true"></i>
							<g:message code="default.button.details.label" />
						</g:link>
					</td>
				</tr>
			</g:each>
			</tbody>
		</table>
		<div class="pagination mi-paginacion-ajax">
			<g:paginate total="${roleInstanceCount ?: 0}" params="${params}"/>
		</div>
	</g:else>

grails-app/views/role/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		
		<div class="col-lg-12">
			<g:hiddenField id="urlBase" name="urlBase" value="${createLink(uri:'/')}" />
			    <div class="ibox float-e-margins">
			        <div class="ibox-title">
			            <h3>
							<g:message code="create.role.label" />
						</h3>
			            <div class="ibox-tools">
			            </div>
			        </div>
			        <div class="ibox-content ">
			           <g:if test="${flash.message}">
							<div class="alert alert-info alert-dismissible" role="alert">
								<button type="button" class="close" data-dismiss="alert">
									<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
								</button>
								${flash.message}
							</div>
						</g:if>
						<div class="container-fluid">
							
							
							<div class="modal-body form-horizontal">
                  				<g:hasErrors bean="${roleInstance}">
									<ul class="errors" role="alert">
										<g:eachError bean="${roleInstance}" var="error">
											<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
										</g:eachError>
									</ul>
								</g:hasErrors>
								<br>
			                  	<fieldset >
				                  	<div >
				                  		<g:form id="${ roleInstance?.id}" action="create" method="POST" >
											<fieldset class="form">
												<g:render template="form"/>
											</fieldset>
											<br>
											<fieldset class="text-center">
												<button id="editButton" class="btn btn-primary" type="submit" >
													
													<g:message code="default.button.create.label" default="Crear" />
												</button>
											</fieldset>
										</g:form>
				                  	</div>
			                  	</fieldset>
			                  
			                </div>
							
							
						</div>
			        </div>
			    </div>
		</div>
		
		<script type="text/javascript">
		var urlBase = $("#urlBase").val();
		$.ajax({
			type : 'GET',
			url : urlBase + 'role/permisos',
			success : function(data) {
				$.each(data, function(i, d) {
	            	$('#permissions').append('<option value="' + d['CODIGO'] + '">' +d['NOMBRE']+ '</option>');	                   
	            });
				$('.chosen-select').chosen({
					no_results_text: '<i class="fa fa-exclamation-circle"></i> No se encontró nigún resultado <i class="fa fa-hand-o-right"></i>',
					allow_single_deselect: true,
					width: "67%"
				});
				
			},
			error : function() { // En caso de error en la petición
				alert('Ups!',"Ocurrió un error en la ejecución del proceso...",'error');
			}
		});
		function alert(title,text,type  ){
			toastr.options = {
		            closeButton: true,
		            progressBar: true,
		            showMethod: 'slideDown',
		            timeOut: 4000
		        };
		    toastr[type](text, title);
		}
		</script>
		
	</body>
</html>

grails-app/views/role/edit.gsp
<%@ page import="jefersson.nunez.boleteria.Role" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		
		<div class="col-lg-12">
			<g:hiddenField id="urlBase" name="urlBase" value="${createLink(uri:'/')}" />
			    <div class="ibox float-e-margins">
			        <div class="ibox-title">
			            <h3>
							<g:message code="edit.role.label" />
						</h3>
			            <div class="ibox-tools">
			            </div>
			        </div>
			        <div class="ibox-content">
			           <g:if test="${flash.message}">
							<div class="alert alert-info alert-dismissible" role="alert">
								<button type="button" class="close" data-dismiss="alert">
									<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
								</button>
								${flash.message}
							</div>
						</g:if>
						<div class="container-fluid">
							
							
							<div class="modal-body form-horizontal">
                  				<g:hasErrors bean="${roleInstance}">
									<ul class="errors" role="alert">
										<g:eachError bean="${roleInstance}" var="error">
											<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
										</g:eachError>
									</ul>
								</g:hasErrors>
								<br>
			                  	<fieldset >
				                  	<div >
				                  		<g:form id="${ roleInstance?.id}" action="edit" method="POST" >
											<g:hiddenField name="version" value="${roleInstance?.version}" />
											<fieldset class="form">
												<g:render template="form"/>
											</fieldset>
											<br>
											<fieldset class="text-center">
												<button id="editButton" class="btn btn-primary" type="submit" >
													
													<g:message code="default.button.update.label" default="Actualizar" />
												</button>
											</fieldset>
										</g:form>
				                  	</div>
			                  	</fieldset>
			                  
			                </div>
							
							
						</div>
			        </div>
			    </div>
		</div>
	
		<script type="text/javascript">
		var urlBase = $("#urlBase").val();
		$('#permissions').empty();
		$.ajax({
			type : 'GET',
			url : urlBase + 'role/permisos',
			success : function(data) {
				
				$.each(data, function(i, d) {
	            	$('#permissions').append('<option value="' + d['CODIGO'] + '">' +d['NOMBRE']+ '</option>');	                   
	            });
				
				var permisos = $('#permisos').val();
				var a = permisos.replace("[" ,'' );
			
				var b = a.replace("]" ,'' );
				
				var bs = b.replace(/\s+/g, "");
				
				var c = bs.split(',');
				
				$('#permissions').val(c);
				
				$('.chosen-select').chosen({
					no_results_text: '<i class="fa fa-exclamation-circle"></i> No se encontró nigún resultado <i class="fa fa-hand-o-right"></i>',
					allow_single_deselect: true,
					width: "67%"
				});
				
			},
			error : function() { // En caso de error en la petición
				alert('Ups!',"Ocurrió un error en la ejecución del proceso...",'error');
			}
		});
		function alert(title,text,type  ){
			toastr.options = {
		            closeButton: true,
		            progressBar: true,
		            showMethod: 'slideDown',
		            timeOut: 4000
		        };
		    toastr[type](text, title);
		}
		</script>
	</body>
</html>

grails-app/views/role/index.gsp
<%@ page import="jefersson.nunez.boleteria.Role" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
		<title><g:message code="role.list.label" /></title>
	</head>
	<body>
		<div class="row">
			<g:hiddenField id="urlBase" name="urlBase" value="${createLink(uri:'/')}" />
		    <div class="col-lg-12">
		        <div class="row">
		        	<div class="ibox float-e-margins">
	                     <div class="ibox-title">
	                         <h5><g:message code="role.list.label" /></h5>
	                     </div>  
						 <div class="ibox-content">
	                          <div class="feed-activity-list">
	                          	
	                                 <div class="row">
	                                 	
	                                 	
						                    <!---------------- Panel de Busqueda ----------------------------------------------------------->	
											<div class="col-lg-8">
												
													<g:form action="search" class="form-horizontal" id="form-search-perfil" name="form-search-perfil">
														<div class="col-xs-12 col-sm-12">
															<div class="input-group">
																<input type="text" class="input-sm form-control search-query" id="query"
																		placeholder="<g:message code="default.placeholder.search.label"/>" name="query"
																		value="${params.query}"> 
																	<span class="input-group-btn">
																		<button type="submit" class="btn btn-sm btn-warning">
																			<g:message code="default.button.search.label"/>
																			<i class=" fa fa-search"></i>
																		</button>
																	</span>
															</div>
														</div>
													</g:form>
												</div>
											
											<!--------------- Termina panel de Busqueda ---------------------------------------------------->
										
							            
	                                 </div>
	                                 <br>
	                                 <div id="div-content-list-perfiles">
	                                 	<g:render template="listPerfiles" ></g:render>
	                                 </div>
	                                  
	                          </div>
	                     </div>
	                </div>
		        </div>
	        </div>
	       
		</div>
	      
	<asset:javascript src="perfiles.js" />
	</body>
</html>

grails-app/views/role/show.gsp
<%@ page import="jefersson.nunez.boleteria.Role" %>
<!doctype html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'role.label', default: 'Perfil')}" />
<title><g:message code="role.title.label" /></title>
<asset:stylesheet src="plugins/sweetalert/sweetalert.css" />
</head>
<body>

	<div class="col-lg-12">
	<g:hiddenField id="urlBase" name="urlBase" value="${createLink(uri:'/')}" />
	    <div class="ibox float-e-margins">
	        <div class="ibox-title">
	            <h3>
					<g:message code="role.header.show.label" />
				</h3>
	            <div class="ibox-tools">
	            </div>
	        </div>
	        <div class="ibox-content ibox-heading">
	           <g:if test="${flash.message}">
					<div class="alert alert-info alert-dismissible" role="alert">
						<button type="button" class="close" data-dismiss="alert">
							<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
						</button>
						${flash.message}
					</div>
				</g:if>
				<div class="container-fluid">
					<div class="col-md-6 col-sm-6">
						<dl>
							<g:if test="${roleInstance?.name}">
								<dt>
									<g:message code="role.name.label" default="Nombre" />
								</dt>
		
								<dd>
									<g:fieldValue bean="${roleInstance}" field="name" />
								</dd>
		
							</g:if>
						</dl>
					</div>
					<div class="col-md-6 col-sm-6">
						<dl>
							<g:if test="${roleInstance?.permissions}">
								<dt>
									<g:message code="role.permissions.label" default="Permisos" />
								</dt>
								<g:each in="${roleInstance.permissions}" status="x" var="permisos">
									<g:each in="${permisosList}" status="ix" var="permi">
										<dd>
											<g:if test="${permi.CODIGO == permisos || permisos == '*:*'}">
												${permi.NOMBRE }
											</g:if>
										</dd>
									</g:each>
								</g:each>
								
							</g:if>
						</dl>
					</div>
				</div>
	        </div>
	        <div class="ibox-content inspinia-timeline">
	
	            <div class="timeline-item">
	                <div class="row">
	                    
	                    <g:form>
							<g:hiddenField name="id" value="${roleInstance?.id}" id="role" />
							<div class="form-actions">
								<g:link id="editButton"
									class="btn btn-info" action="edit"
									id="${roleInstance?.id}">
									<i class="fa fa-pencil"></i>
									<g:message code="default.button.edit.label" default="Editar" />
								</g:link>
								<button id="deleteButton" class="btn btn-danger demo4" type="button" >
									<i class="fa fa-trash"></i>
									<g:message code="default.button.delete.label" default="Delete" />
								</button>
							</div>
						</g:form>
	                    
	                </div>
	            </div>
	           
	           
	            
	
	        </div>
	    </div>
	</div>
	
<asset:javascript src="plugins/sweetalert/sweetalert.min.js" />
<script type="text/javascript">
	var urlBase = $("#urlBase").val();
	$('.demo4').click(function () {
		var title = '<g:message code="default.sure.delete.label"/>'
		var text = '<g:message code="default.text.delete.label"/>'
		var confirmButtonText = '<g:message code="default.confirmButtonText.label"/>'
		var cancelButtonText = '<g:message code="default.cancelButtonText.label"/>'
	    swal({
	                title: title,
	                text: text,
	                type: "warning",
	                showCancelButton: true,
	                confirmButtonColor: "#DD6B55",
	                confirmButtonText: confirmButtonText,
	                cancelButtonText: cancelButtonText,
	                closeOnConfirm: false,
	                closeOnCancel: false },
	            function (isConfirm) {
	                if (isConfirm) {
	                    $.ajax({
	            			type:'POST',
	            			url : urlBase + 'role/delete',
	            			data : {'id':$('#role').val()},
	            			success : function(data) {
	            				if (!data.ErrorUpdate) {
	            					swal('<g:message code="default.deleted.label"/>', '<g:message code="default.deleted.text.label"/>', "success");
	            					setTimeout($(location).attr('href', urlBase+'role/index'), 1000);
	            				}else{
	            					swal('<g:message code="default.error.label"/>', data.error , "error");
	            				}
	            			},
	            			error : function() { // En caso de error en la petición
	            				swal('<g:message code="default.error.label"/>','<g:message code="default.error.ajax.label"/>' ,'error');
	            			}
	            		});
	                } else {
	                    swal('<g:message code="default.cancelled.label"/>', '<g:message code="default.cancelled.text.label"/>', "error");
	                }
	            });
	});
</script>
</body>
</html>