grails-app/domain/jefersson/nunez/boleteria/Boleto.groovy
package jefersson.nunez.boleteria

class Boleto {
	static searchable = true
	Double valor
	Evento evento
	Tipo tipo
	
    static constraints = {
		
    }
	
	static mapping = {
		version false
		table 'BOLETO'
		id generator:'native'
		columns{
			id column:'ID'
			valor column:'valor'
			evento column:'evento'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/Cliente.groovy
package jefersson.nunez.boleteria

class Cliente {
	static searchable = true
	Long cedula
	String nombre
	String telefono
	String correo

    static constraints = {
		
    }
	
	static mapping = {
		version false
		table 'CLIENTE'
		id generator:'native'
		columns{
			id column:'id'
			cedula column:'cedula'
			nombre column:'nombre'
			correo column:'correo'
			telefono column:'telefono'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/Evento.groovy
package jefersson.nunez.boleteria

class Evento {
	static searchable = true
	String nombre
	String direccion
	String ciudad
	Date fecha
	Long cantidadBoletos

    static constraints = {
		nombre(nullable: false, blank: false)
		direccion(nullable: false, blank: false)
		ciudad(nullable: false, blank: false)
		fecha(nullable: false, blank: false)
		cantidadBoletos(nullable: false, blank: false)
    }
	static mapping = {
		version false
		table 'EVENTO'
		id generator:'native'
		columns{
			id column:'id'
			nombre column:'nombre'
			direccion column:'direccion'
			ciudad column:'ciudad'
			fecha column:'fecha'
			cantidadBoletos column:'cantidadBoletos'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/Reserva.groovy
package jefersson.nunez.boleteria

class Reserva {
	static searchable = true
	Cliente cliente
	Boleto boleto
	Date fecha
	Long cantidadBoletos
	
    static constraints = {
    }
	
	static mapping = {
		version false
		table 'RESERVA'
		id generator:'native'
		columns{
			id column:'id'
			cliente column:'cliente'
			boleto column:'boleto'
			fecha column:'fecha'
			cantidadBoletos column:'cantidadBoletos'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/Role.groovy
package jefersson.nunez.boleteria

/**
 * The Role entity.
 *
 * @author  Jefersson Nava
 * @version 1.0.0
 * @since
 *
 */
class Role {
	static searchable = true
    String name

    static hasMany = [ users: User, permissions: String ]
    static belongsTo = User

    static constraints = {
        name(nullable: false, blank: false, unique: true)
    }
	
	static mapping = {
		version false
		table 'ROLE'
		id generator:'native'
		columns{
			id column:'ID'
			name column:'nombre'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/Tipo.groovy
package jefersson.nunez.boleteria

class Tipo {
	static searchable = true
	String nombre

    static constraints = {
    }
	static mapping = {
		version false
		table 'TIPO'
		id generator:'native'
		columns{
			id column:'ID'
			nombre column:'valor'
		}
	}
}

grails-app/domain/jefersson/nunez/boleteria/User.groovy
package jefersson.nunez.boleteria

/**
 * The User entity.
 *
 * @author  Jefersson Nava
 * @version 1.0.0
 * @since
 *
 */
class User {
	static searchable = true
	
    String username
    String passwordHash
	
	String nombre
	String apellido
    String telefono
	String fechaRegistro
	String habilitado = "S"
	
    static hasMany = [ roles: Role ]

    static constraints = {
        username(nullable: false, blank: false, unique: true)
		passwordHash nullable:false, blank:false
		nombre nullable: false, blank: false, size:1..100
		apellido nullable: true, blank: true, size:0..100
		habilitado nullable:false, blank:false, size:0..1, inList:["S","N"]
		fechaRegistro nullable:true, blank:true, size:0..1024
		telefono nullable:true, blank:true, size:1..20
    }
	
	static mapping = {
		version false
		table 'USUARIO'
		id generator:'native'
		columns{
			id column:'ID'
			username column:'usuario'
			passwordHash column:'clave'
			nombre column:'nombre'
			apellido column:'apellido'
			telefono column:'telefono'
			fechaRegistro column:'fechaRegistro'
			habilitado column:'habilitado'
		}
	}
}

grails-app/controllers/jefersson/nunez/boleteria/AuthController.groovy
package jefersson.nunez.boleteria

import org.apache.shiro.SecurityUtils
import org.apache.shiro.authc.AuthenticationException
import org.apache.shiro.authc.UsernamePasswordToken
import org.apache.shiro.web.util.SavedRequest
import org.apache.shiro.web.util.WebUtils

class AuthController {
    def shiroSecurityManager

    def index = { redirect(action: "login", params: params) }

    def login = {
        return [ username: params.username, rememberMe: (params.rememberMe != null), targetUri: params.targetUri ]
    }

    def signIn = {
        def authToken = new UsernamePasswordToken(params.username, params.password as String)

        // Support for "remember me"
        if (params.rememberMe) {
            authToken.rememberMe = true
        }
        
        // If a controller redirected to this page, redirect back
        // to it. Otherwise redirect to the root URI.
        def targetUri = params.targetUri ?: "/"
        
        // Handle requests saved by Shiro filters.
        SavedRequest savedRequest = WebUtils.getSavedRequest(request)
        if (savedRequest) {
            targetUri = savedRequest.requestURI - request.contextPath
            if (savedRequest.queryString) targetUri = targetUri + '?' + savedRequest.queryString
        }
        
        try{
            // Perform the actual login. An AuthenticationException
            // will be thrown if the username is unrecognised or the
            // password is incorrect.
            SecurityUtils.subject.login(authToken)

            log.info "Redirecting to '${targetUri}'."
            redirect(uri: targetUri)
        }
        catch (AuthenticationException ex){
            // Authentication failed, so display the appropriate message
            // on the login page.
            log.info "Authentication failure for user '${params.username}'."
            flash.message = message(code: "login.failed")

            // Keep the username and "remember me" setting so that the
            // user doesn't have to enter them again.
            def m = [ username: params.username ]
            if (params.rememberMe) {
                m["rememberMe"] = true
            }

            // Remember the target URI too.
            if (params.targetUri) {
                m["targetUri"] = params.targetUri
            }

            // Now redirect back to the login page.
            redirect(action: "login", params: m)
        }
    }

    def signOut = {
        // Log the user out of the application.
        SecurityUtils.subject?.logout()
        webRequest.getCurrentRequest().session = null

        // For now, redirect back to the home page.
        redirect(uri: "/")
    }

    def unauthorized = {
        render "You do not have permission to access this page."
    }
}

grails-app/views/user/_errors.gsp
<g:hasErrors bean="${flash.errors}">
   
      <g:eachError bean="${flash.errors}" var="error">
        <li
          <g:if test="${error in org.springframework.validation.FieldError}"></g:if>><g:message error="${error}" /></li>
      </g:eachError>
   
</g:hasErrors>

grails-app/views/user/_form.gsp
<%@ page import="jefersson.nunez.boleteria.User" %>



<div class="hidden">
  <input type="password"/>
</div>
      
<input type="hidden" name="query" id="params-query" value="${params.query }" />

<div class="form-group ${hasErrors(bean: userInstance, field: 'nombre', 'error')} required">
	<label for="name" class="col-sm-4 control-label">
		<g:message code="user.name.label" default="Nombre" />
		<span class="required-indicator">*</span>
	</label>
	<div class="col-sm-8">
		<g:textField name="nombre" class="input-sm col-xs-8 col-sm-8" required="" value="${userInstance?.nombre}"/>
	</div>
</div>

<div class="form-group ${hasErrors(bean: userInstance, field: 'apellido', 'error')} required">
	<label for="lastName" class="col-sm-4 control-label">
		<g:message code="user.lastName.label" default="Apellido" />
	</label>
	<div class="col-sm-8">
		<g:textField name="apellido" class="input-sm col-xs-8 col-sm-8" value="${userInstance?.apellido}"/>
	</div>
</div>

<div class="form-group ${hasErrors(bean: userInstance, field: 'username', 'error')} required">
	<label for="username" class="col-sm-4 control-label">
		<g:message code="user.username.label" default="Usuario" />
		<span class="required-indicator">*</span>
	</label>
	<div class="col-sm-8">
		<g:textField name="username" class="input-sm col-xs-8 col-sm-8" required="" value="${userInstance?.username}"/>
	</div>
</div>

<div class="div-content-password">
	<div class="form-group ${hasErrors(bean: userInstance, field: 'passwordHash', 'error')} required">
		<label for="passwordHash" class="col-sm-4 control-label">
			<g:message code="user.passwordHash.label" default="Contraseña" />
			<span class="required-indicator">*</span>
		</label>
		<div class="col-sm-8">
			<input name="passwordHash" type="password" class="input-sm col-xs-8 col-sm-8" readonly onfocus="this.removeAttribute('readonly');" value="${userInstance?.passwordHash}"/>
		</div>
	</div>
</div>

<div class="form-group ${hasErrors(bean: userInstance, field: 'telefono', 'error')} required">
	<label for="eMail" class="col-sm-4 control-label">
		<g:message code="user.telefono.label" default="Teléfono" />
		<span class="required-indicator">*</span>
	</label>
	<div class="col-sm-8">
		<input type="text" name="telefono" class="input-sm col-xs-8 col-sm-8" required="required" autocomplete="off" value="${userInstance?.telefono}">
	</div>
</div>




<div class="form-group ${hasErrors(bean: userInstance, field: 'roles', 'error')} ">
	<label for="roles" class="col-sm-4 control-label">
		<g:message code="user.roles.label" default="Perfiles" />
	</label>
	<div class="col-sm-8">
		<g:select name="roles" from="${roleInstanceList}" multiple="true" data-placeholder="Ninguno" optionKey="id" optionValue="name" value="${userInstance?.roles*.id}" class="chosen-select"/>
	</div>
</div>

grails-app/views/user/_listUsuarios.gsp
	<g:if test="${flash.message}">
		<div class="message" role="status">${flash.message}</div>
	</g:if>
	<g:if test="${userInstanceList.empty}">
		<p id="noEntries"><g:message code="default.noEntries.label"/></p>
	</g:if>
	<g:else>
		<div class="table-responsive"> 
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th class="mail-box check-mail"><input type="checkbox" value="" name="" class="i-checks" disabled/></th>
						<th class="text-center"><g:message code="user.name.label" /></th>
						<th class="text-center"><g:message code="user.lastName.label" /></th>
						<th class="text-center"><g:message code="user.telefono.label" /></th>
						<th class="text-center"><g:message code="user.username.label" /></th>
						<th class="text-center"><g:message code="user.roles.label" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${userInstanceList}" status="i" var="userInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'} fil" data-id="${userInstance.id }">
						
						<td>
							<input type="checkbox" value="" name="ckeckbox-usuarios" class="i-checks" data-id="${userInstance.id }" ${userInstance.username == 'superAdmin' ? 'disabled' : ''}/>
	                                      					 
						</td>
						<td class="text-center">
							<g:link action="show" id="${userInstance?.id}">${fieldValue(bean: userInstance, field: "nombre")}
							</g:link>
						</td>
						<td class="text-center">${fieldValue(bean: userInstance, field: "apellido")}</td>
						<td class="text-center">${fieldValue(bean: userInstance, field: "telefono")}</td>
						<td class="text-center">${fieldValue(bean: userInstance, field: "username")}</td>
						
						<td class="text-center">
							<g:each in="${userInstance?.roles}" status="x" var="role">
								${role.name },
							</g:each>
						</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
		</div>
		<div class="pagination mi-paginacion-ajax">
			<g:paginate total="${userInstanceCount ?: 0}" params="${params}"/>
		</div>
	</g:else>

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-user" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${userInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:userInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/user/edit.gsp
<%@ page import="jefersson.nunez.boleteria.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-user" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${userInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:userInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${userInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/user/index.gsp
<%@ page import="jefersson.nunez.boleteria.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuarios')}" />
		<title><g:message code="user.label" /></title>
	</head>
	<body>
		
		<div class="row">
			<g:hiddenField id="urlBase" name="urlBase" value="${createLink(uri:'/')}" />
			<link href="${g.resource(dir: 'assets/images', file: 'camera.png', absolute: true)}" id="link-src-camera"/>
		    <div class="col-lg-12">
		        <div class="row">
		        	<div class="ibox float-e-margins">
	                     <div class="ibox-title">
	                         <h5><g:message code="user.label" /></h5>
	                     </div>  
						 <div class="ibox-content">
	                          <div class="feed-activity-list">
	                          	
	                                 <div class="row">
	                                 	
	                                 	
						                    <!---------------- Panel de Busqueda ----------------------------------------------------------->	
											<div class="col-lg-8">
												
													<g:form action="search" class="form-horizontal" id="form-search-usuario" name="form-search-usuario">
														<div class="col-xs-12 col-sm-12">
															<div class="input-group">
																<input type="text" class="input-sm form-control search-query" id="query"
																		placeholder="<g:message code="default.placeholder.search.label"/>" name="query"
																		value="${params.query}"> 
																	<span class="input-group-btn">
																		<button type="submit" class="btn btn-sm btn-warning">
																			<g:message code="default.button.search.label"/>
																			<i class=" fa fa-search"></i>
																		</button>
																	</span>
															</div>
														</div>
													</g:form>
												</div>
											
											<!--------------- Termina panel de Busqueda ---------------------------------------------------->
											<div class="container-fluid col-lg-4 pull-right tooltip-demo">
												
												<button class="btn btn-success btn-outline" type="button" id="btn-adicionar-usuario"
															data-toggle="tooltip" title="<g:message code="default.tooltip.create.label"/>" data-placement="top" ><i class="fa fa-plus"></i></button>
												<button class="btn btn-danger btn-outline" type="button" id="btn-eliminar-usuario"
															data-toggle="tooltip" title="<g:message code="default.tooltip.delete.label"/>" data-placement="top" ><i class="fa fa-times"></i></button>
												<button class="btn btn-info btn-outline" type="button" id="btn-editar-usuario"
															data-toggle="tooltip" title="<g:message code="default.tooltip.edit.label"/>" data-placement="top" ><i class="fa fa-pencil"></i></button>
												
											</div>
										
							            
	                                 </div>
	                                 <br>
	                                 <div id="div-content-list-usuarios">
	                                 	<g:render template="listUsuarios" ></g:render>
	                                 </div>
	                                  
	                          </div>
	                     </div>
	                </div>
		        </div>
	        </div>
	       
		</div>
		
	  <!-- MODAL CREAR 	USUARIO -->   
      <div class="modal inmodal" id="modal-adicionar-usuario" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog">
          	<g:form class="form-horizontal" name="form-create-usuario" autocomplete="off" enctype="multipart/form-data">
	          <div class="modal-content animated bounceInRight">
                  <div class="modal-header">
                      <button type="button" class="close btn-modal-cerrar" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                      <h4 class="modal-title"><g:message code="user.create.label" /></h4>
                  </div>
                  <div class="modal-body form-horizontal">
                  
                  	<fieldset >
	                  	<div id="div-content-form-create-usuario">
	                  		
	                  	</div>
                  	</fieldset>
                  
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-white btn-modal-cerrar" data-dismiss="modal"><g:message code="default.cerrar.label" /></button>
                      <button type="submit" class="btn btn-primary btn-guardar-modal"><g:message code="default.save.label" /></button>
                  </div>
	           </div>
          	</g:form>
          </div>
      </div>
	
	<!-- MODAL EDITAR USUARIO -->   
      <div class="modal inmodal" id="modal-editar-usuario" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog">
          	<g:form class="form-horizontal" name="form-edit-user" autocomplete="off" enctype="multipart/form-data">
	          <div class="modal-content animated bounceInRight">
	                  <div class="modal-header">
	                      <button type="button" class="close btn-modal-cerrar" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	                      <h4 class="modal-title"><g:message code="user.edit.label" /></h4>
	                  </div>
	                  <div class="modal-body form-horizontal">
	                  
	                  	<fieldset >
		                  	<div id="div-content-form-edit-usuario">
		                  		
		                  	</div>
	                  	</fieldset>
	                  
	                  </div>
	                  <div class="modal-footer">
	                      <button type="button" class="btn btn-white btn-modal-cerrar" data-dismiss="modal"><g:message code="default.cerrar.label" /></button>
	                      <button type="submit" class="btn btn-primary btn-guardar-modal"><g:message code="default.save.label" /></button>
	                  </div>
	              </div>
	          	</g:form>
	          </div>
	      </div>
	      
	  <!-- MODAL ELIMINAR USUARIO -->   
      <div class="modal inmodal" id="modal-eliminar-usuario" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog">
	          <div class="modal-content animated bounceInRight">
	                  <div class="modal-header">
	                      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	                      <h4 class="modal-title"><g:message code="user.delete.label" /></h4>
	                  </div>
	                  <div class="modal-body form-horizontal">
	                  
	                  	<fieldset >
		                  	<div id="div-content-delete-usuario">
		                  		
		                  	</div>
	                  	</fieldset>
	                  
	                  </div>
	                  <div class="modal-footer">
	                      <button type="button" class="btn btn-white" data-dismiss="modal"><g:message code="default.cerrar.label" /></button>
	                      <button type="button" class="btn btn-danger btn-confirmar-eliminar-usuario btn-guardar-modal"><g:message code="default.delete.label" /></button>
	                  </div>
	              </div>
	          </div>
	      </div>
	      
	      <!-- MODAL FOTO USUARIO -->   
      <div class="modal inmodal" id="modal-foto" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog">
	          <div class="modal-content animated bounceInRight">
                  <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                      <h4 class="modal-title"><g:message code="user.photo.label" /></h4>
                  </div>
                  <div class="modal-body form-horizontal">
                  
                  	<div class="text-center">
						<img id="imagen-modal-foto"
							class="editable img-responsive editable-empty img-thumbnail"
							src="" />
					</div>
                  
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-white" data-dismiss="modal"><g:message code="default.cerrar.label" /></button>
                  </div>
              </div>
          </div>
      </div>
	      
	<asset:javascript src="jquery.form.js" />
	<asset:javascript src="usuarios.js" />
	</body>
</html>

grails-app/views/user/show.gsp
<%@ page import="jefersson.nunez.boleteria.User" %>
<!doctype html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'user.label', default: 'Usuario')}" />
<title><g:message code="user.title.label" /></title>
<asset:stylesheet src="plugins/sweetalert/sweetalert.css" />
</head>
<body>

	<div class="col-lg-12">
	<g:hiddenField id="urlBase" name="urlBase" value="${createLink(uri:'/')}" />
	    <div class="ibox float-e-margins">
	        <div class="ibox-title">
	            <h3>
					<g:message code="user.header.show.label" />
				</h3>
	            <div class="ibox-tools">
	            </div>
	        </div>
	        <div class="ibox-content ibox-heading">
	           <g:if test="${flash.message}">
					<div class="alert alert-info alert-dismissible" role="alert">
						<button type="button" class="close" data-dismiss="alert">
							<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
						</button>
						${flash.message}
					</div>
				</g:if>
				<div class="container-fluid">
					<div class="col-md-6 col-sm-6">
						<dl>
							<g:if test="${userInstance?.nombre}">
								<dt>
									<g:message code="user.name.label" default="Nombre" />
								</dt>
		
								<dd>
									<g:fieldValue bean="${userInstance}" field="nombre" />
								</dd>
		
							</g:if>
						</dl>
					</div>
					<div class="col-md-6 col-sm-6">
						<dl>
							<g:if test="${userInstance?.apellido}">
								<dt>
									<g:message code="user.lastName.label" default="lastName" />
								</dt>
		
								<dd>
									<g:fieldValue bean="${userInstance}" field="apellido" />
								</dd>
		
							</g:if>
						</dl>
					</div>
					<div class="col-md-6 col-sm-6">
						<dl>
							<g:if test="${userInstance?.username}">
								<dt>
									<g:message code="user.username.label" default="Nombre" />
								</dt>
		
								<dd>
									<g:fieldValue bean="${userInstance}" field="username" />
								</dd>
		
							</g:if>
						</dl>
					</div>
					<div class="col-md-6 col-sm-6">
						<dl>
							<g:if test="${userInstance?.telefono}">
								<dt>
									<g:message code="user.telefono.label" default="Email" />
								</dt>
		
								<dd>
									<g:fieldValue bean="${userInstance}" field="telefono" />
								</dd>
		
							</g:if>
						</dl>
					</div>
					
				</div>
	        </div>
	        <div class="ibox-content inspinia-timeline">
	
	            <div class="timeline-item">
	                <div class="row">
	                    
	                    
	                    
	                </div>
	            </div>
	           
	           
	            
	
	        </div>
	    </div>
	</div>
	
</body>
</html>